### ISSUE TITLE
Traffic getting stuck time to time.

### ISSUE THREAD

**Issue by marintoro** [dianchen96/LearningByCheating#8]
Hello,
I discovered something strange when I test your trained agent on dense No-Crash scenario.
Time to time the traffic gets totally stuck and the episode cannot be solved anymore (the road to the target position is blocked by other vehicles). I think the issue is coming from the function "start_dtcrowd" which is not working as expected.
Could you confirm that the function "start_dtcrowd" should take care of traffic getting stuck by respawning vehicle being stuck for too long?
And did you ever got this issue and how to solve it? (as I am using cuda10.1 and not cuda8 as in the config file, I didn't install all the environment.yml dependencies but installed by hand all libraries needed to make the exemple script to work and maybe I missed one important libraries).

**Comment by dotchen** [comment]
Hi @marintoro ,

Thanks for bringing this up. The `start_dtcrowd` simply adds the pedestrian handles to the crowd manager, such that pedestrians avoid the cars. It does not take care of traffic getting stuck.

We found that the traffic deadlock is indeed an issue in the `dense` NoCrash scenario, especially in Town2. In our implementation we did not teleport the cars if they are stuck, because that would make the numbers unfair comparing to the reported numbers in CILRS which is the baseline. In fact, the traffic deadlock is the main reason even the [ground-truth autopilot](https://github.com/dianchen96/LearningByCheating#autopilot-1) cannot get reasonable numbers in `dense` NoCrash. 

Please let us know if you have more questions :D
